SELECT R1.REST_ID,
    R1.REST_NAME,
    R1.FOOD_TYPE,
    R1.FAVORITES,
    R1.ADDRESS,
    ROUND(AVG(R2.REVIEW_SCORE), 2) SCORE
FROM REST_INFO R1
JOIN REST_REVIEW R2
ON R1.REST_ID = R2.REST_ID
WHERE R1.REST_ID = R2.REST_ID
    AND R1.ADDRESS LIKE '서울%'
GROUP BY R1.REST_ID,
    R1.REST_NAME,
    R1.FOOD_TYPE,
    R1.FAVORITES,
    R1.ADDRESS
ORDER BY SCORE DESC,
    R1.FAVORITES DESC
    